[package]
authors = ["Taryn Hill <taryn@phrohdoh.com>"]
name = "server"
version = "0.0.1"

[dependencies]
futures = "0.1.17"
hyper = "0.11.7"
serde = "1.0.23"
serde_json = "1.0.6"
structopt = "0.1.6"
structopt-derive = "0.1.6"

[dependencies.github_webhook_data]
path = "../"
