[package]
authors = ["Taryn Hill <taryn@phrohdoh.com>"]
name = "server"
version = "0.0.1"

[dependencies]
futures = "0.1"
hyper = "0.11"
serde = "1.0"
serde_json = "1.0"
structopt = "0.1"
structopt-derive = "0.1"

[dependencies.github_webhook_data]
path = "../"
